2019-06-25 14:20:31 - INFO - werkzeug[line:87]:  * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
2019-06-25 14:20:50 - INFO - werkzeug[line:87]: 127.0.0.1 - - [25/Jun/2019 14:20:50] "[33mGET / HTTP/1.1[0m" 404 -
2019-06-25 14:20:51 - INFO - werkzeug[line:87]: 127.0.0.1 - - [25/Jun/2019 14:20:51] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2019-06-25 16:54:20 - ERROR - bin.app[line:75]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 66, in correlation
    data = json.loads(request.data)
  File "/Users/apple/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-25 16:55:04 - ERROR - bin.app[line:75]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 66, in correlation
    data = json.loads(request.data)
  File "/Users/apple/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-25 16:57:53 - ERROR - bin.app[line:75]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 66, in correlation
    data = json.loads(request.data)
  File "/Users/apple/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-25 17:07:54 - ERROR - bin.app[line:75]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 66, in correlation
    data = json.loads(request.data)
  File "/Users/apple/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-25 17:09:33 - INFO - werkzeug[line:87]:  * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
2019-06-25 17:10:06 - ERROR - bin.app[line:76]: 'bytes' object has no attribute 'copy'
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 68, in correlation
    data = time_delayed_correlation_analysis.get_normalized_samples(data)
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/mods/time_delayed_correlation_analysis.py", line 18, in get_normalized_samples
    data = data.copy()
AttributeError: 'bytes' object has no attribute 'copy'
2019-06-25 17:10:57 - ERROR - bin.app[line:77]: 'bytes' object has no attribute 'copy'
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 69, in correlation
    data = time_delayed_correlation_analysis.get_normalized_samples(data)
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/mods/time_delayed_correlation_analysis.py", line 18, in get_normalized_samples
    data = data.copy()
AttributeError: 'bytes' object has no attribute 'copy'
2019-06-25 17:13:34 - ERROR - bin.app[line:79]: 'bytes' object has no attribute 'copy'
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 71, in correlation
    data = time_delayed_correlation_analysis.get_normalized_samples(data)
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/mods/time_delayed_correlation_analysis.py", line 18, in get_normalized_samples
    data = data.copy()
AttributeError: 'bytes' object has no attribute 'copy'
2019-06-25 17:14:23 - ERROR - bin.app[line:79]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 69, in correlation
    data = json.loads(request.data)
  File "/Users/apple/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-25 17:24:50 - ERROR - bin.app[line:78]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 68, in correlation
    data = json.loads(request.data)
  File "/Users/apple/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-25 17:25:17 - INFO - werkzeug[line:87]:  * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
2019-06-25 17:25:38 - ERROR - bin.app[line:78]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 68, in correlation
    data = json.loads(request.data)
  File "/Users/apple/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-25 17:34:26 - ERROR - bin.app[line:47]: 'dict' object has no attribute 'drop'
Traceback (most recent call last):
  File "/Users/luolei/Documents/Git_Repository_Dreisteine/chrissun99_pollution_forcast/bin/app.py", line 39, in correlation
    data = time_delayed_correlation_analysis.get_normalized_samples(data)
  File "/Users/luolei/Documents/Git_Repository_Dreisteine/chrissun99_pollution_forcast/mods/time_delayed_correlation_analysis.py", line 19, in get_normalized_samples
    data.drop(['ptime', 'time_stamp'], axis = 1, inplace = True)
AttributeError: 'dict' object has no attribute 'drop'
2019-06-25 17:40:47 - ERROR - bin.app[line:46]: 'dict' object has no attribute 'drop'
Traceback (most recent call last):
  File "/Users/luolei/Documents/Git_Repository_Dreisteine/chrissun99_pollution_forcast/bin/app.py", line 38, in correlation
    data = time_delayed_correlation_analysis.get_normalized_samples(data)
  File "/Users/luolei/Documents/Git_Repository_Dreisteine/chrissun99_pollution_forcast/mods/time_delayed_correlation_analysis.py", line 19, in get_normalized_samples
    data.drop(['ptime', 'time_stamp'], axis = 1, inplace = True)
AttributeError: 'dict' object has no attribute 'drop'
2019-06-25 17:43:58 - ERROR - bin.app[line:46]: 'dict' object has no attribute 'drop'
Traceback (most recent call last):
  File "/Users/luolei/Documents/Git_Repository_Dreisteine/chrissun99_pollution_forcast/bin/app.py", line 38, in correlation
    data = time_delayed_correlation_analysis.get_normalized_samples(data)
  File "/Users/luolei/Documents/Git_Repository_Dreisteine/chrissun99_pollution_forcast/mods/time_delayed_correlation_analysis.py", line 19, in get_normalized_samples
    data.drop(['ptime', 'time_stamp'], axis = 1, inplace = True)
AttributeError: 'dict' object has no attribute 'drop'
2019-06-25 17:45:22 - ERROR - bin.app[line:47]: 'dict' object has no attribute 'drop'
Traceback (most recent call last):
  File "/Users/luolei/Documents/Git_Repository_Dreisteine/chrissun99_pollution_forcast/bin/app.py", line 39, in correlation
    data = time_delayed_correlation_analysis.get_normalized_samples(data)
  File "/Users/luolei/Documents/Git_Repository_Dreisteine/chrissun99_pollution_forcast/mods/time_delayed_correlation_analysis.py", line 19, in get_normalized_samples
    data.drop(['ptime', 'time_stamp'], axis = 1, inplace = True)
AttributeError: 'dict' object has no attribute 'drop'
2019-06-25 17:45:54 - ERROR - bin.app[line:47]: 'dict' object has no attribute 'drop'
Traceback (most recent call last):
  File "/Users/luolei/Documents/Git_Repository_Dreisteine/chrissun99_pollution_forcast/bin/app.py", line 39, in correlation
    data = time_delayed_correlation_analysis.get_normalized_samples(data)
  File "/Users/luolei/Documents/Git_Repository_Dreisteine/chrissun99_pollution_forcast/mods/time_delayed_correlation_analysis.py", line 19, in get_normalized_samples
    data.drop(['ptime', 'time_stamp'], axis = 1, inplace = True)
AttributeError: 'dict' object has no attribute 'drop'
2019-06-25 17:46:22 - ERROR - bin.app[line:47]: 'dict' object has no attribute 'drop'
Traceback (most recent call last):
  File "/Users/luolei/Documents/Git_Repository_Dreisteine/chrissun99_pollution_forcast/bin/app.py", line 39, in correlation
    data = time_delayed_correlation_analysis.get_normalized_samples(data)
  File "/Users/luolei/Documents/Git_Repository_Dreisteine/chrissun99_pollution_forcast/mods/time_delayed_correlation_analysis.py", line 19, in get_normalized_samples
    data.drop(['ptime', 'time_stamp'], axis = 1, inplace = True)
AttributeError: 'dict' object has no attribute 'drop'
2019-06-25 17:47:54 - ERROR - bin.app[line:47]: 'list' object has no attribute 'drop'
Traceback (most recent call last):
  File "/Users/luolei/Documents/Git_Repository_Dreisteine/chrissun99_pollution_forcast/bin/app.py", line 39, in correlation
    data = get_normalized_samples(data['data'])
  File "/Users/luolei/Documents/Git_Repository_Dreisteine/chrissun99_pollution_forcast/mods/time_delayed_correlation_analysis.py", line 19, in get_normalized_samples
    data.drop(['ptime', 'time_stamp'], axis = 1, inplace = True)
AttributeError: 'list' object has no attribute 'drop'
2019-06-25 17:53:20 - ERROR - bin.app[line:47]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 37, in correlation
    data = json.loads(request.data)['data']
  File "/Users/apple/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-25 17:53:38 - INFO - werkzeug[line:87]:  * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
2019-06-25 17:54:55 - ERROR - bin.app[line:46]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 36, in correlation
    data = json.loads(request.data)['data']
  File "/Users/apple/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-25 18:05:05 - INFO - werkzeug[line:87]:  * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
2019-06-25 18:05:11 - INFO - werkzeug[line:87]:  * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
2019-06-25 18:05:32 - ERROR - bin.app[line:46]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 36, in correlation
    data = json.loads(request.data)['data']
  File "/Users/apple/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-25 18:16:17 - ERROR - bin.app[line:47]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 37, in correlation
    data = json.loads(request.data)['data']
  File "/Users/apple/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-25 18:21:35 - ERROR - bin.app[line:47]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 37, in correlation
    data = json.loads(request.data)
  File "/Users/apple/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-25 18:22:04 - ERROR - bin.app[line:47]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 37, in correlation
    data = json.loads(request.data)
  File "/Users/apple/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-25 18:24:49 - ERROR - bin.app[line:46]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 36, in correlation
    data = json.loads(request.data)
  File "/Users/apple/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-25 18:25:39 - ERROR - bin.app[line:47]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 37, in correlation
    data = json.loads(request.data)
  File "/Users/apple/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-25 18:26:32 - ERROR - bin.app[line:47]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/apple/Desktop/pollution_statistic_forecast_app-develop_lstm/bin/app.py", line 37, in correlation
    data = json.loads(request.data)
  File "/Users/apple/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/apple/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
